import { cities, models, names } from './data.js';
export const STARTS = [300000,500000,1000000,3000000,10000000];
const pick = (a, r) => a[Math.floor(r()*a.length)];
const weightedPick = (items, weight, r) => { const weights=items.map(weight), total=weights.reduce((a,b)=>a+b,0); let roll=r()*total; for(let i=0;i<items.length;i++){roll-=weights[i];if(roll<0)return items[i]} return items.at(-1); };
const rng = seed => { let x=seed>>>0; return () => ((x=(x+0x6D2B79F5)|0, Math.imul(x^x>>>15,1|x), x^=x+Math.imul(x^x>>>7,61|x), ((x^x>>>14)>>>0)/4294967296)); };
export const rub = n => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
export const city = id => cities.find(c=>c.id===id);
export function marketValue(model, year, km, condition, cityData, day){ const age=Math.max(0,2026-year), ageFactor=Math.max(.52,1-age*.018), kmFactor=Math.max(.7,1-Math.max(0,km-age*9000)/400000*.16), conditionFactor=.72+condition*.28, demandFactor=.7+Math.max(.7,Math.min(1.3,cityData.demand))*.3, brandFactor=.94+model.liquidity*.05, season=1+Math.sin((day%365)/365*Math.PI*2)*.025; return Math.round(model.base*ageFactor*kmFactor*conditionFactor*cityData.market*demandFactor*brandFactor*season/10000)*10000; }
export function createGame(cash, seed=Date.now()){ const home='msk'; const state={version:1,seed,randomState:seed|0,marketCycle:0,player:{name:'Частный перекуп',home,cash,account:0}, day:0, minute:8*60, phase:'market', listings:[], inventory:[], logs:[], offer:null, selected:null, slots:[], lastDeal:null}; state.listings=generateListings(state,12); return state; }
const classifyIssue = issue => /корроз|скол|кузов|днищ|арок|двер|капот|порог|рама|стекл|салон/i.test(issue)?'body':/подвес|рулев|тормоз|мост|раздат|сцеплен|шарнир|амортиз/i.test(issue)?'chassis':/короб|вариатор|акпп|мкпп|трансмисс/i.test(issue)?'transmission':/датчик|электр|катуш|дроссел|катализатор|ошиб/i.test(issue)?'electrical':'engine';
export function restoreGame(candidate){if(!candidate||candidate.version!==1||!candidate.player||!Number.isFinite(candidate.player.cash)||!Array.isArray(candidate.listings)||!Array.isArray(candidate.inventory)||!Array.isArray(candidate.logs))return null;const modelIds=new Set(models.map(m=>m.id)),cityIds=new Set(cities.map(c=>c.id)),seed=Number.isFinite(candidate.seed)?candidate.seed:1,validCar=car=>car&&typeof car.id==='string'&&modelIds.has(car.modelId)&&cityIds.has(car.cityId);const normalizeListing=car=>{const hidden=Array.isArray(car.hidden)?car.hidden.filter(x=>typeof x==='string'):[];return {...car,hidden,categories:car.categories||Object.fromEntries(hidden.map(issue=>[issue,classifyIssue(issue)])),seller:car.seller||{urgency:.35,greed:.5,rapport:.35,rounds:0},found:Array.isArray(car.found)?car.found:[],diagRuns:car.diagRuns||0,diagnosticsCost:car.diagnosticsCost||0,publishedDay:car.publishedDay??candidate.day??0,publishedMinute:car.publishedMinute??candidate.minute??480,status:car.status||(car.trip?'viewing':'active'),tripCost:car.tripCost||0};};return {...candidate,seed,randomState:Number.isFinite(candidate.randomState)?candidate.randomState:seed,marketCycle:Number.isFinite(candidate.marketCycle)?candidate.marketCycle:0,day:Number.isFinite(candidate.day)?Math.max(0,Math.floor(candidate.day)):0,minute:Number.isFinite(candidate.minute)?Math.max(0,Math.min(1439,Math.floor(candidate.minute))):480,phase:['market','garage','map','ledger'].includes(candidate.phase)?candidate.phase:'market',player:{...candidate.player,name:typeof candidate.player.name==='string'?candidate.player.name:'Частный перекуп',home:cityIds.has(candidate.player.home)?candidate.player.home:'msk',account:Number.isFinite(candidate.player.account)?candidate.player.account:0},listings:candidate.listings.filter(validCar).map(normalizeListing),inventory:candidate.inventory.filter(validCar).map(car=>({...car,tripCost:car.tripCost||0,diagnosticsCost:car.diagnosticsCost||0,repairs:car.repairs||0,history:Array.isArray(car.history)?car.history:[],buyerOfferBy:car.buyerOfferBy||null,buyerOfferDay:car.buyerOfferDay??null})),logs:candidate.logs.filter(log=>log&&Number.isFinite(log.amount)&&typeof log.description==='string'),selected:typeof candidate.selected==='string'?candidate.selected:null,slots:[]};}
export function generateListings(s,count=9){ const cycle=s.marketCycle||0,r=rng(s.randomState+s.day*1009+cycle*37), origin=city(s.player.home); return Array.from({length:count},(_,i)=>{let m=pick(models,r), c=weightedPick(cities,region=>region.demand*(region.popular.includes(m.brand)?1.3:.8),r), year=Math.round(m.from+r()*(Math.min(m.to,2026)-m.from)), km=Math.round((2026-year)*(6500+r()*9000)/1000)*1000, cond=.68+r()*.46, fair=marketValue(m,year,km,cond,c,s.day), ask=Math.round(fair*(.91+r()*.2)/10000)*10000, possible=[...m.issues.split(', '),...m.bodyIssues.split(', ')], hidden=possible.filter(()=>r()<.48); if(!hidden.length) hidden=[pick(possible,r)]; return {id:`${s.seed}-${s.day}-${cycle}-${i}`,modelId:m.id,cityId:c.id,year,km,condition:cond,ask,fair,hidden,categories:Object.fromEntries(hidden.map(issue=>[issue,classifyIssue(issue)])),owner:pick(names,r),seller:{urgency:r(),greed:r(),rapport:.2+r()*.5,rounds:0},owners:1+Math.floor(r()*4),description:pick(['Собственник, торг у капота.','На ходу, вложений по мелочи.','Обмен не интересует.','Цена обсуждается после осмотра.'],r),distance:distance(origin,c),publishedDay:s.day,publishedMinute:s.minute,status:'active',inspected:false,diag:0,diagRuns:0,diagnosticsCost:0,found:[],trip:false,offer:null};}); }
export function distance(a,b){ const dx=(a.x-b.x)*90,dy=(a.y-b.y)*90; return Math.round(Math.hypot(dx,dy)); }
export function advance(s,minutes){ if(!Number.isFinite(minutes)||minutes<0)return false;s.minute+=minutes; while(s.minute>=1440){s.minute-=1440;s.day++;}return true; }
export function spend(s,amount,description){ if(!Number.isFinite(amount)||amount<0||amount>s.player.cash)return false;s.player.cash-=amount;if(amount>0)s.logs.unshift({day:s.day,description,amount:-amount});return true; }
const diagCost = kind => kind==='obd'?8500:kind==='service'?24000:0;
const diagMinutes = kind => kind==='obd'?45:kind==='service'?120:30;
export function examine(s,id,kind){ const car=s.listings.find(x=>x.id===id); if(!car||!car.trip)return {error:'Сначала нужно приехать к продавцу.'}; if(!['visual','obd','service'].includes(kind))return {error:'Неизвестный вид диагностики.'}; const cost=diagCost(kind); if(!spend(s,cost,kind==='visual'?'Визуальный осмотр':kind==='obd'?'Компьютерная диагностика OBD':'Комплексная диагностика в сервисе'))return {error:'Недостаточно средств.'}; car.diagnosticsCost=(car.diagnosticsCost||0)+cost;advance(s,diagMinutes(kind));car.diagRuns=(car.diagRuns||0)+1;car.found=car.found||[];const rngCheck=rng(s.seed+car.id.length*71+car.diagRuns*997+(kind==='visual'?13:kind==='obd'?29:47));const eligible=car.hidden.filter(issue=>{const category=car.categories?.[issue]||classifyIssue(issue);return kind==='visual'?category==='body':kind==='obd'?category==='electrical'||(/катализатор|охлажд|термостат/i.test(issue)&&category==='engine'):true});const rate=kind==='visual'?.76:kind==='obd'?.68:.78;const found=eligible.filter(issue=>!car.found.includes(issue)&&rngCheck()<rate);car.found.push(...found);car.inspected=true;car.diag=Math.max(car.diag,kind==='visual'?1:kind==='obd'?2:3);return {findings:found,cost,minutes:diagMinutes(kind),examined:eligible.length}; }
const sellerFloor = car => {const seller=car.seller||{urgency:.35,greed:.5,rapport:.35};return Math.min(car.ask,Math.max(car.fair*.65,car.fair*(.77+.16*seller.greed-.12*seller.urgency-.035*seller.rapport+(1-car.condition)*.05)));};
export function negotiate(s,id,offer){ const car=s.listings.find(x=>x.id===id); if(!car||!car.trip)return {error:'Нужно находиться у продавца.'}; if(!Number.isFinite(offer)||offer<0)return {error:'Укажите корректную сумму.'}; advance(s,10);const seller=car.seller||(car.seller={urgency:.35,greed:.5,rapport:.35,rounds:0}),floor=sellerFloor(car);seller.rounds++;if(offer>=floor){car.offer=offer;return {accepted:true,price:offer};}const gap=Math.max(0,car.ask-offer),concession=.22+seller.urgency*.28+seller.rapport*.16+(1-seller.greed)*.12;car.offer=Math.min(car.ask,Math.ceil(Math.max(floor,offer+gap*concession)/10000)*10000);seller.rapport=Math.min(1,seller.rapport+.035);return {accepted:false,counter:car.offer}; }
export function tripQuote(distanceKm){const km=Math.max(0,distanceKm);return {cost:1000+Math.round(km*1.7)+Math.round(km/650)*4200,minutes:Math.max(180,Math.ceil(km/65)*60),hours:Math.max(3,Math.ceil(km/70))};}
export function travelToListing(s,id){const car=s.listings.find(x=>x.id===id);if(!car||car.status==='sold')return {error:'Объявление больше недоступно.'};if(car.trip)return {error:'Вы уже находитесь у продавца.'};const quote=tripQuote(car.distance);if(!spend(s,quote.cost,`Поездка к продавцу в ${city(car.cityId).name}`))return {error:`Для поездки нужно ${rub(quote.cost)}.`};advance(s,quote.minutes);car.trip=true;car.tripCost=quote.cost;car.status='viewing';return {quote,car};}
export function buy(s,id,price){ const car=s.listings.find(x=>x.id===id), model=models.find(m=>m.id===car?.modelId); if(!car||!car.trip||!model)return {error:'Сделка недоступна.'}; if(!Number.isFinite(price)||price<=0)return {error:'Цена покупки должна быть больше нуля.'};if(car.offer!==price)return {error:'Сначала согласуйте цену с продавцом.'}; const paperwork=Math.round(price*.012)+6500, shipping=Math.max(5000,Math.round(car.distance*72)); const total=price+paperwork+shipping; if(!spend(s,total,`Покупка, оформление и доставка ${model.brand} ${model.model}`))return {error:`Нужно ${rub(total)} с учётом доставки и оформления.`}; advance(s,Math.round(car.distance/50*60)+240); const bought={...car,purchasePrice:price,tripCost:car.tripCost||0,diagnosticsCost:car.diagnosticsCost||0,delivery:shipping,paperwork,repairs:0,stage:'garage',status:'owned',history:[`День ${s.day}: покупка у ${car.owner}`,`Поездка к продавцу: ${rub(car.tripCost||0)}`,`Диагностика: ${rub(car.diagnosticsCost||0)}`,`Оформление: ${rub(paperwork)}`,`Доставка: ${rub(shipping)}`],ask:0}; s.inventory.push(bought);s.listings=s.listings.filter(x=>x.id!==id);s.selected=bought.id;s.phase='garage';return {bought,total}; }
export function repairCost(home,kind){const c=city(home);return Math.round((kind==='service'?42000:12000)*c.service)}
export function repair(s,id,kind){ const car=s.inventory.find(x=>x.id===id); if(!car||car.stage!=='garage')return {error:'Автомобиль недоступен для ремонта.'}; const m=models.find(x=>x.id===car.modelId), c=city(s.player.home); const cost=repairCost(s.player.home,kind);if(!spend(s,cost,kind==='service'?'Ремонт в сервисе':'Самостоятельный ремонт и расходники'))return {error:'Недостаточно средств.'};advance(s,kind==='service'?360:240);car.repairs+=cost;car.condition=Math.min(1.08,car.condition+(kind==='service'?.2:.09));car.history.push(`День ${s.day}: ${kind==='service'?'ремонт в сервисе':'самостоятельный ремонт'} — ${rub(cost)}`);return {cost}; }
export function listForSale(s,id,price){const car=s.inventory.find(x=>x.id===id);if(!car||car.stage!=='garage')return {error:'Автомобиль недоступен.'};if(!Number.isFinite(price)||price<10000)return {error:'Цена должна быть не меньше 10 000 ₽.'};car.ask=Math.max(10000,Math.round(price/10000)*10000);car.stage='listed';car.listedDay=s.day;car.messages=0;car.history.push(`День ${s.day}: объявление размещено за ${rub(car.ask)}`);s.phase='garage';advance(s,5);return {ok:true};}
export function updateAsk(s,id,price){const car=s.inventory.find(x=>x.id===id&&x.stage==='listed');if(!car)return {error:'Нет активного объявления.'};if(!Number.isFinite(price)||price<=0)return {error:'Цена должна быть больше нуля.'};const next=Math.max(10000,Math.round(price/10000)*10000),previous=car.ask;if(next===previous)return {ok:true,changed:false,price:next};const offerCleared=Number.isFinite(car.buyerOffer);car.ask=next;car.buyerOffer=null;car.buyerOfferBy=null;car.buyerOfferDay=null;advance(s,5);car.history.push(`День ${s.day}: цена объявления изменена с ${rub(previous)} на ${rub(next)}`);return {ok:true,changed:true,previous,price:next,offerCleared};}
export function buyers(s,id){const car=s.inventory.find(x=>x.id===id&&x.stage==='listed');if(!car)return {error:'Сначала разместите объявление.'};const r=rng(s.seed+car.listedDay*773+car.messages*101+car.id.length);advance(s,720+Math.floor(r()*720));car.messages++;const m=models.find(x=>x.id===car.modelId),region=city(car.cityId);const competing=s.listings.filter(x=>x.cityId===car.cityId&&x.modelId===car.modelId).length+s.inventory.filter(x=>x.id!==car.id&&x.stage==='listed'&&x.cityId===car.cityId&&x.modelId===car.modelId).length;const priceInterest=Math.max(.12,Math.min(.88,.63-(car.ask-car.fair)/car.fair*.9));const brandDemand=region.popular.includes(m.brand)?1.12:.9;const supplyFactor=1/(1+competing*.16);const interest=Math.max(.08,Math.min(.92,priceInterest*m.liquidity*region.demand*brandDemand*supplyFactor));const interested=r()<interest;const price=interested?Math.round(car.ask*(.91+r()*.07)/10000)*10000:0;const buyer=interested?pick(names,r):null;if(interested){car.buyerOffer=price;car.buyerOfferBy=buyer;car.buyerOfferDay=s.day;}return {interested,price,interest,competing,days:Math.floor((s.day-car.listedDay)),buyer};}
export function sell(s,id,price){const car=s.inventory.find(x=>x.id===id&&x.stage==='listed');if(!car)return {error:'Нет активного объявления.'};if(!Number.isFinite(price)||!Number.isFinite(car.buyerOffer)||price!==car.buyerOffer)return {error:'Продать можно только по действующему предложению покупателя.'};if(s.day-(car.buyerOfferDay??s.day)>3){car.buyerOffer=null;car.buyerOfferBy=null;car.buyerOfferDay=null;return {error:'Предложение покупателя истекло. Подождите нового.'};}advance(s,30);const revenue=price, cost=dealCost(car), profit=revenue-cost; s.player.cash+=revenue;s.logs.unshift({day:s.day,description:`Продажа ${models.find(m=>m.id===car.modelId).brand} ${models.find(m=>m.id===car.modelId).model}`,amount:revenue});car.stage='sold';car.status='sold';car.salePrice=revenue;car.profit=profit;car.history.push(`День ${s.day}: продан ${car.buyerOfferBy||'покупателю'} за ${rub(revenue)}. Результат сделки: ${rub(profit)}`);s.lastDeal={profit,revenue,cost,name:`${models.find(m=>m.id===car.modelId).brand} ${models.find(m=>m.id===car.modelId).model}`};s.phase='market';s.selected=null;return {profit};}
export function dealCost(car){return (car.tripCost||0)+(car.diagnosticsCost||0)+(car.purchasePrice||0)+(car.delivery||0)+(car.paperwork||0)+(car.repairs||0);}
export function inventoryValue(s){return s.inventory.filter(c=>c.stage!=='sold').reduce((sum,c)=>sum+marketValue(models.find(m=>m.id===c.modelId),c.year,c.km,c.condition,city(s.player.home),s.day),0);}
export function netWorth(s){return s.player.cash+s.player.account+inventoryValue(s);}
