import { cities, models, names } from './data.js';
export const STARTS = [300000,500000,1000000,3000000,10000000];
const pick = (a, r) => a[Math.floor(r()*a.length)];
const weightedPick = (items, weight, r) => { const weights=items.map(weight), total=weights.reduce((a,b)=>a+b,0); let roll=r()*total; for(let i=0;i<items.length;i++){roll-=weights[i];if(roll<0)return items[i]} return items.at(-1); };
const rng = seed => { let x=seed>>>0; return () => ((x=(x+0x6D2B79F5)|0, Math.imul(x^x>>>15,1|x), x^=x+Math.imul(x^x>>>7,61|x), ((x^x>>>14)>>>0)/4294967296)); };
export const rub = n => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
export const city = id => cities.find(c=>c.id===id);
export function marketValue(model, year, km, condition, cityData, day){ const age=Math.max(0,2026-year), ageFactor=Math.max(.52,1-age*.018), kmFactor=Math.max(.7,1-Math.max(0,km-age*9000)/400000*.16), conditionFactor=.72+condition*.28, demandFactor=.7+Math.max(.7,Math.min(1.3,cityData.demand))*.3, brandFactor=.94+model.liquidity*.05, season=1+Math.sin((day%365)/365*Math.PI*2)*.025; return Math.round(model.base*ageFactor*kmFactor*conditionFactor*cityData.market*demandFactor*brandFactor*season/10000)*10000; }
export function createGame(cash, seed=Date.now()){ const home='msk'; const state={version:1,seed,randomState:seed|0,marketCycle:0,player:{name:'Частный перекуп',home,cash,account:0}, day:0, minute:8*60, phase:'market', listings:[], inventory:[], logs:[], offer:null, selected:null, slots:[], lastDeal:null}; state.listings=generateListings(state,12); return state; }
export function generateListings(s,count=9){ const cycle=s.marketCycle||0,r=rng(s.randomState+s.day*1009+cycle*37), origin=city(s.player.home); return Array.from({length:count},(_,i)=>{let m=pick(models,r), c=weightedPick(cities,region=>region.demand*(region.popular.includes(m.brand)?1.3:.8),r), year=Math.round(m.from+r()*(Math.min(m.to,2020)-m.from)), km=Math.round((2026-year)*(6500+r()*9000)/1000)*1000, cond=.68+r()*.46, fair=marketValue(m,year,km,cond,c,s.day), ask=Math.round(fair*(.91+r()*.2)/10000)*10000, issues= m.issues.split(', '), hidden=issues.filter(()=>r()<.48); if(!hidden.length) hidden=[pick(issues,r)]; return {id:`${s.seed}-${s.day}-${cycle}-${i}`,modelId:m.id,cityId:c.id,year,km,condition:cond,ask,fair,hidden,owner:pick(names,r),owners:1+Math.floor(r()*4),description:pick(['Собственник, торг у капота.','На ходу, вложений по мелочи.','Обмен не интересует.','Цена обсуждается после осмотра.'],r),distance:distance(origin,c),inspected:false,diag:0,trip:false,offer:null};}); }
export function distance(a,b){ const dx=(a.x-b.x)*90,dy=(a.y-b.y)*90; return Math.round(Math.hypot(dx,dy)); }
export function advance(s,minutes){ s.minute+=minutes; while(s.minute>=1440){s.minute-=1440;s.day++;} }
export function spend(s,amount,description){ if(amount>s.player.cash)return false;s.player.cash-=amount;s.logs.unshift({day:s.day,description,amount:-amount});return true; }
export function examine(s,id,kind){ const car=s.listings.find(x=>x.id===id); if(!car||!car.trip)return {error:'Сначала нужно приехать к продавцу.'}; const cost=kind==='obd'?8500:kind==='service'?24000:0; if(!spend(s,cost,kind==='obd'?'Компьютерная диагностика OBD':'Комплексная диагностика в сервисе'))return {error:'Недостаточно средств.'}; advance(s,kind==='service'?120:kind==='obd'?45:30); car.inspected=true; const found=kind==='visual'?car.hidden.slice(0,1):kind==='obd'?car.hidden.slice(0,2):car.hidden; car.diag=Math.max(car.diag,kind==='visual'?1:kind==='obd'?2:3); return {findings:found}; }
export function negotiate(s,id,offer){ const car=s.listings.find(x=>x.id===id); if(!car||!car.trip)return {error:'Нужно находиться у продавца.'}; if(!Number.isFinite(offer)||offer<0)return {error:'Укажите корректную сумму.'}; advance(s,10); const limit=car.fair*(.83+car.condition*.07); if(offer<limit){car.offer=Math.round(Math.max(limit,offer+(car.fair-offer)*.43)/10000)*10000;return {accepted:false,counter:car.offer};} if(offer<=car.ask*1.04){car.offer=offer;return {accepted:true,price:offer};} return {accepted:false,counter:car.ask}; }
export function buy(s,id,price){ const car=s.listings.find(x=>x.id===id), model=models.find(m=>m.id===car?.modelId); if(!car||!car.trip||!model)return {error:'Сделка недоступна.'}; if(!Number.isFinite(price)||price<=0)return {error:'Цена покупки должна быть больше нуля.'}; const paperwork=Math.round(price*.012)+6500, shipping=Math.max(5000,Math.round(car.distance*72)); const total=price+paperwork+shipping; if(!spend(s,total,`Покупка, оформление и доставка ${model.brand} ${model.model}`))return {error:`Нужно ${rub(total)} с учётом доставки и оформления.`}; advance(s,Math.round(car.distance/50*60)+240); const bought={...car,purchasePrice:price,tripCost:car.tripCost||0,delivery:shipping,paperwork,repairs:0,stage:'garage',history:[`День ${s.day}: покупка у ${car.owner}`,`Поездка к продавцу: ${rub(car.tripCost||0)}`,`Оформление: ${rub(paperwork)}`,`Доставка: ${rub(shipping)}`],ask:0}; s.inventory.push(bought);s.listings=s.listings.filter(x=>x.id!==id);s.selected=bought.id;s.phase='garage';return {bought,total}; }
export function repairCost(home,kind){const c=city(home);return Math.round((kind==='service'?42000:12000)*c.service)}
export function repair(s,id,kind){ const car=s.inventory.find(x=>x.id===id); if(!car||car.stage!=='garage')return {error:'Автомобиль недоступен для ремонта.'}; const m=models.find(x=>x.id===car.modelId), c=city(s.player.home); const cost=repairCost(s.player.home,kind);if(!spend(s,cost,kind==='service'?'Ремонт в сервисе':'Самостоятельный ремонт и расходники'))return {error:'Недостаточно средств.'};advance(s,kind==='service'?360:240);car.repairs+=cost;car.condition=Math.min(1.08,car.condition+(kind==='service'?.2:.09));car.history.push(`День ${s.day}: ${kind==='service'?'ремонт в сервисе':'самостоятельный ремонт'} — ${rub(cost)}`);return {cost}; }
export function listForSale(s,id,price){const car=s.inventory.find(x=>x.id===id);if(!car||car.stage!=='garage')return {error:'Автомобиль недоступен.'};if(!Number.isFinite(price)||price<=0)return {error:'Цена должна быть больше нуля.'};car.ask=Math.round(price/10000)*10000;car.stage='listed';car.listedDay=s.day;car.messages=0;car.history.push(`День ${s.day}: объявление размещено за ${rub(car.ask)}`);s.phase='garage';advance(s,5);return {ok:true};}
export function updateAsk(s,id,price){const car=s.inventory.find(x=>x.id===id&&x.stage==='listed');if(!car)return {error:'Нет активного объявления.'};if(!Number.isFinite(price)||price<=0)return {error:'Цена должна быть больше нуля.'};const next=Math.max(10000,Math.round(price/10000)*10000),previous=car.ask;if(next===previous)return {ok:true,changed:false,price:next};const offerCleared=Number.isFinite(car.buyerOffer);car.ask=next;car.buyerOffer=null;advance(s,5);car.history.push(`День ${s.day}: цена объявления изменена с ${rub(previous)} на ${rub(next)}`);return {ok:true,changed:true,previous,price:next,offerCleared};}
export function buyers(s,id){const car=s.inventory.find(x=>x.id===id&&x.stage==='listed');if(!car)return {error:'Сначала разместите объявление.'};const r=rng(s.seed+car.listedDay*773+car.messages*101+car.id.length);advance(s,720+Math.floor(r()*720));car.messages++;const m=models.find(x=>x.id===car.modelId),region=city(car.cityId);const competing=s.listings.filter(x=>x.cityId===car.cityId&&x.modelId===car.modelId).length+s.inventory.filter(x=>x.id!==car.id&&x.stage==='listed'&&x.cityId===car.cityId&&x.modelId===car.modelId).length;const priceInterest=Math.max(.12,Math.min(.88,.63-(car.ask-car.fair)/car.fair*.9));const brandDemand=region.popular.includes(m.brand)?1.12:.9;const supplyFactor=1/(1+competing*.16);const interest=Math.max(.08,Math.min(.92,priceInterest*m.liquidity*region.demand*brandDemand*supplyFactor));const interested=r()<interest;const price=interested?Math.round(car.ask*(.91+r()*.07)/10000)*10000:0;if(interested)car.buyerOffer=price;return {interested,price,interest,competing,days:Math.floor((s.day-car.listedDay)),buyer:pick(names,r)};}
export function sell(s,id,price){const car=s.inventory.find(x=>x.id===id&&x.stage==='listed');if(!car)return {error:'Нет активного объявления.'};if(!Number.isFinite(price)||price<car.ask*.75)return {error:'Покупатель не согласен: предложение слишком низкое.'};advance(s,30);const revenue=price, cost=(car.tripCost||0)+car.purchasePrice+car.delivery+car.paperwork+car.repairs, profit=revenue-cost; s.player.cash+=revenue;s.logs.unshift({day:s.day,description:`Продажа ${models.find(m=>m.id===car.modelId).brand} ${models.find(m=>m.id===car.modelId).model}`,amount:revenue});car.stage='sold';car.salePrice=revenue;car.profit=profit;car.history.push(`День ${s.day}: продан за ${rub(revenue)}. Результат сделки: ${rub(profit)}`);s.lastDeal={profit,revenue,cost,name:`${models.find(m=>m.id===car.modelId).brand} ${models.find(m=>m.id===car.modelId).model}`};s.phase='market';s.selected=null;return {profit};}
export function netWorth(s){return s.player.cash+s.player.account+s.inventory.filter(c=>c.stage!=='sold').reduce((sum,c)=>sum+marketValue(models.find(m=>m.id===c.modelId),c.year,c.km,c.condition,city(s.player.home),s.day),0);}
